spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
