spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swapswap
    username: root
    password: 1322
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

jwt:
  secret:
    key: ${JwtSecretKey}
